from motive import app
import pytest


@pytest.fixture
def api():
    api = app.test_client()
    return api


@pytest.fixture
def category_options():
    return [
            "Afghan",
            "African",
            "American",
            "Arepa",
            "Argentinian",
            "Armenian",
            "Asian",
            "Australian",
            "Austrian",
            "Bangladeshi",
            "Belarusian",
            "Belgian",
            "Bosnian",
            "Brazilian",
            "Bulgarian",
            "Burmese",
            "Cajun",
            "Cambodian",
            "Caribbean",
            "Caucasian",
            "Chinese",
            "Colombian",
            "Cuban",
            "Czech",
            "Dumpling",
            "Dutch",
            "Eastern European",
            "Egyptian",
            "Empanada",
            "English",
            "Ethiopian",
            "Falafel",
            "Fast Food",
            "Filipino",
            "French",
            "German",
            "Greek",
            "Halal",
            "Hawaiian",
            "Himalayan",
            "Honduran",
            "Hotpot",
            "Hungarian",
            "Indian",
            "Indonesian",
            "Iraqi",
            "Israeli",
            "Japanese",
            "Italian",
            "Jewish",
            "Kebab",
            "Korean",
            "Kurdish",
            "Latin American",
            "Lebanese",
            "Malay",
            "Mauritian",
            "Mediterranean",
            "Mexican",
            "Middle Eastern",
            "Modern European",
            "Molecular Gastronomy",
            "Mongolian",
            "Moroccan",
            "New American",
            "Noodle",
            "Pakistani",
            "Persian",
            "Peruvian",
            "Polish",
            "Portuguese",
            "Poutine",
            "Puerto Rican",
            "Romanian",
            "Russian",
            "Salad",
            "Salvadoran",
            "Sandwich",
            "Satay",
            "Scandinavian",
            "Scottish",
            "Seafood",
            "Shawarma",
            "Singaporean",
            "Slovak",
            "Soup",
            "South American",
            "Southern",
            "Spanish",
            "Sri Lankan",
            "Swiss",
            "Syrian",
            "Tatar",
            "Thai",
            "Tibetan",
            "Turkish",
            "Ukrainian",
            "Vegan and Vegetarian",
            "Venezuelan",
            "Vietnamese",
            "Yemeni",
            "all"
        ]

